baseURL = 'https://yourusername.github.io/blog/'
languageCode = 'en-us'
title = 'Working Notes'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showCodeCopyButtons = true

  [params.assets]
    favicon = "favicon.svg"
    favicon16x16 = "favicon.svg"
    favicon32x32 = "favicon.svg"
    apple_touch_icon = "favicon.svg"

